name: Build site into docs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Astro build
        run: npx astro build --site https://tamermansour-ai.github.io/Tamer-Portfolio/

      - name: Copy dist → docs
        run: |
          rm -rf docs
          cp -R dist docs

      - name: Commit docs folder
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Astro build -> docs" || echo "No changes"
          git push origin main
