name: Deploy to GitHub Pages

# Trigger the workflow on pushes to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout the code
      - uses: actions/checkout@v3

      # 2) Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies
      - run: npm install

      # 4) Build the site (Eleventy outputs to dist/)
      - run: npx @11ty/eleventy

      # 5) Deploy dist/ to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist          # مجلد التصدير النسبي
          publish_branch: gh-pages   # فرع GitHub Pages
          force_orphan: true
