name: Deploy Astro with GitHub Pages

# يعمل مع كل دفعة على main أو يدويًا
on:
  push:
    branches: [main]
  workflow_dispatch:

# الصلاحيات المطلوبة لـ Pages
permissions:
  contents: read        # للسحب
  pages: write          # للنشر
  id-token: write       # للتحقق

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx astro build --site ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

      # ✨ ارفع مجلّد dist كأرتيفاكت إلى خطوة النشر
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # ينشر الأرتيفاكت ويعطيك الرابط
      - id: deployment
        uses: actions/deploy-pages@v4
